version: '3.8'
services:

  db:
    env_file:
      - .env
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always

  backend:
    image: rezts/foodgram:latest
    restart: always
    depends_on:
      - db
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
      - ../data/:/app/data/
    env_file:
      - ./.env

  frontend:
    image: rezts/foodgram_frontend:latest
    volumes:
      - result_build:/app/result_build/build/
    depends_on:
      - backend

  nginx:
    image: nginx:1.19.3
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - result_build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - frontend

volumes:
  result_build:
  postgres_data:
  static_value:
  media_value: